services:
  postgres:
    image: postgres:17
    container_name: giretra-postgres
    environment:
      POSTGRES_USER: giretra_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      GIRETRA_DB_PASSWORD: ${GIRETRA_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U giretra_admin"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - tetezana
    ports:
      - 54111:5432

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: giretra-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: auth.giretra.com
      KC_HTTP_PORT: 8080
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true

      # Social identity providers
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tetezana

volumes:
  pgdata:

networks:
  tetezana:
    external: true
